version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000" 
    volumes:
      - ./backend:/app
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development

  frontend:
    build: ./frontend
    ports:
      - "8080:80" 
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/share/nginx/html
